
// This file has been generated by the GUI designer. Do not modify.
namespace TicTacToe
{
	public partial class CellButton
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TicTacToe.CellButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TicTacToe.CellButton";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
